'use server';

/**
 * @fileOverview A Genkit flow that refines an existing code review summary.
 *
 * - refineReviewSummary - A function that refines the review summary.
 * - RefineReviewSummaryInput - The input type for the refineReviewSummary function.
 * - RefineReviewSummaryOutput - The return type for the refineReviewSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefineReviewSummaryInputSchema = z.string().describe('The initial code review generated by another AI agent.');
export type RefineReviewSummaryInput = z.infer<typeof RefineReviewSummaryInputSchema>;

const RefineReviewSummaryOutputSchema = z.string().describe('A refined, more polished version of the code review.');
export type RefineReviewSummaryOutput = z.infer<typeof RefineReviewSummaryOutputSchema>;

export async function refineReviewSummary(input: RefineReviewSummaryInput): Promise<RefineReviewSummaryOutput> {
  return refineReviewSummaryFlow(input);
}

const refineReviewSummaryFlow = ai.defineFlow(
  {
    name: 'refineReviewSummaryFlow',
    inputSchema: RefineReviewSummaryInputSchema,
    outputSchema: RefineReviewSummaryOutputSchema,
  },
  async (initialReview) => {
    const prompt = `You are a Principal Software Engineer acting as a quality filter. Your task is to review and refine an AI-generated pull request summary.

The goal is to make the review more concise, ensure it has a professional and encouraging tone, and verify that the structure (Summary, Potential Issues, Suggestions) is clear. Add a final concluding sentence to wrap up the review positively.

Do not alter the core technical points, but improve the language and presentation.

Here is the initial review:
---
${initialReview}
---

Provide only the refined Markdown as your output.
`;

    const { text } = await ai.generate({
      prompt: prompt,
      model: 'googleai/gemini-2.5-flash',
    });
    return text!;
  }
);
