'use server';

/**
 * @fileOverview A Genkit flow that refines an existing code review summary.
 *
 * - refineReviewSummary - A function that refines the review summary.
 * - RefineReviewSummaryInput - The input type for the refineReviewSummary function.
 * - RefineReviewSummaryOutput - The return type for the refineReviewSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RefineReviewSummaryInputSchema = z.string().describe('The initial code review generated by another AI agent.');
export type RefineReviewSummaryInput = z.infer<typeof RefineReviewSummaryInputSchema>;

const RefineReviewSummaryOutputSchema = z.string().describe('A refined, more polished version of the code review.');
export type RefineReviewSummaryOutput = z.infer<typeof RefineReviewSummaryOutputSchema>;

export async function refineReviewSummary(input: RefineReviewSummaryInput): Promise<RefineReviewSummaryOutput> {
  return refineReviewSummaryFlow(input);
}

const refineReviewSummaryFlow = ai.defineFlow(
  {
    name: 'refineReviewSummaryFlow',
    inputSchema: RefineReviewSummaryInputSchema,
    outputSchema: RefineReviewSummaryOutputSchema,
  },
  async (initialReview) => {
    const promptText = "You are a Principal Software Engineer acting as a quality filter. Your task is to review and refine an AI-generated pull request summary."
      + "\n\nThe goal is to make the review more concise, professional, and helpful. "
      + "\n\nCRITICAL REQUIREMENTS:"
      + "\n1. Preserve priority tags [High], [Medium], and [Low]."
      + "\n2. Preserve file/line metadata like [File: path/to/file.ts] [Line: 123]."
      + "\n3. Ensure that in 'Potential Issues', the description and the **Suggestion:** are kept together in the same bullet point."
      + "\n4. Maintain the structure: Summary, Potential Issues, and Generic Suggestions."
      + "\n5. Add a final positive concluding sentence."
      + "\n\nHere is the initial review:\n"
      + "---\n"
      + initialReview
      + "\n---\n"
      + "\nProvide only the refined Markdown as your output.\n";

    const { text } = await ai.generate({
      prompt: promptText,
      model: 'googleai/gemini-2.5-flash',
    });
    return text!;
  }
);